dist: xenial
language: java
jdk:
- openjdk8
cache:
  directories:
  - "$HOME/.m2"
script: mvn clean package

after_success:
-  sh set_tags.sh

deploy:
  provider: releases
  api_key:
    secure: $RELEASES_SECURE_KEY
  file: target/springmvcexample.war
  skip_cleanup: true
  on:
    branch: master
    repo: bingaru/springexamplemvc
